version: '3.8'

services:
    frontend:
        build: ../example-frontend
        ports:
            - 4000:4000
        container_name: frontend

    backend:
        build: ../example-backend
        ports:
            - 8080:8080
        container_name: backend

    cache:
        image: redis:latest
        container_name: redis
