version: '3.8'

services:
    simple-web-service:
        image: devopsdockeruh/simple-web-service:ubuntu
        command: ['server']
        ports:
            - 8080:8080
        container_name: exercise_2.2
